SELECT * FROM sklep.users;

-- INSERT INTO SKLEP.USERS (ID,USERNAME, PASSWORD, ROLE) VALUES ('103', 'admin', 'pass', 'ROLE_ADMIN');

-- DELETE FROM SKLEP.USERS WHERE ID = 103;

-- UPDATE SKLEP.USERS SET PASSWORD = '$2a$10$ylsYyvnabBTb/9z8Khugx.kCEaZUQolAZ0vStnQBiWrmOhuqVH6xe' WHERE SKLEP.USERS.ID = 103;


