SELECT * FROM sklep.users;

SELECT * FROM SKLEP.CATEGORY, SKLEP.USERS;



-- INSERT INTO SKLEP.USERS (ID,USERNAME, PASSWORD, ROLE) VALUES ('103', 'admin', 'pass', 'ROLE_ADMIN');

-- DELETE FROM SKLEP.USERS WHERE ID = 103;

-- UPDATE SKLEP.USERS SET PASSWORD = '$2a$10$ylsYyvnabBTb/9z8Khugx.kCEaZUQolAZ0vStnQBiWrmOhuqVH6xe' WHERE SKLEP.USERS.ID = 103;

SELECT MAX(c.id) FROM Category c ORDER BY c.code DESC LIMIT 1;

SELECT * from CATEGORY;

UPDATE sklep.CATEGORY
SET code = 'K2'
WHERE ID = 402;

select * from sklep.product;
